#!/usr/bin/env python
# coding=utf-8

import rospy
import auv324_csv_parser

if __name__ == '__main__':
    rospy.init_node('auv324_csv_parser_node', anonymous=True)

    try:
        auv324_csv_parser.auv324OutlineControl('auv324', True, '/home/wz9562/Documents/catkin_arms/src/auv_controller/csv/T20210508.csv', '2021-05-08')
    except rospy.ROSInterruptException:
        print('<auv324_csv_parser_node>: catch exception, interrupt')
        pass

