#!/usr/bin/env python
# coding=utf-8

import rospy
import auv324_db_parser

if __name__ == '__main__':
    try:
        db_parser = auv324_db_parser.auv324DBParser('T20210531')
        db_parser.parse_db('../db/AUV_DB_20210531')
        param_list = db_parser.get_params()

        auv324_db_parser.plotAUV324Param(param_list, '../plt/')

    except Exception, er:
        print(er)
        pass


